/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119881-g9ad6dca28c-20250612"
#endif /* AVUTIL_FFVERSION_H */
